name: Slack Research
favicon: null
layout_spectrum: 0.50131
typography_spectrum: 0.36843702499754727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8744452542159706
  lightness: 0.1720612004864961
  saturation: 0.4482265254482627
  rhythmicContrast: 0.3037428199313581
purpose: []
