name: Slack Research
favicon: null
layout_spectrum: 0.74009
typography_spectrum: 0.36843702499754727
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#53b990'
    - '#d70e62'
    - '#e2a700'
    - '#35103a'
  brandStrength: 1
  lightness: 0.1720612004864961
  saturation: 0.4482265254482627
  rhythmicContrast: 0.3037428199313581
purpose: []
